/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "erg1.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
erg1_prog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		pin_args eswt_ginom_1_arg;
		pin_args averages_1_arg;
		ginom_r_args ginom_r_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case ESWT_GINOM:
		_xdr_argument = (xdrproc_t) xdr_pin_args;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) eswt_ginom_1_svc;
		break;

	case AVERAGES:
		_xdr_argument = (xdrproc_t) xdr_pin_args;
		_xdr_result = (xdrproc_t) xdr_averages_ret;
		local = (char *(*)(char *, struct svc_req *)) averages_1_svc;
		break;

	case GINOM_R:
		_xdr_argument = (xdrproc_t) xdr_ginom_r_args;
		_xdr_result = (xdrproc_t) xdr_ginom_r_ret;
		local = (char *(*)(char *, struct svc_req *)) ginom_r_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (ERG1_PROG, ERG1_VERS);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, ERG1_PROG, ERG1_VERS, erg1_prog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (ERG1_PROG, ERG1_VERS, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, ERG1_PROG, ERG1_VERS, erg1_prog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (ERG1_PROG, ERG1_VERS, tcp).");
		exit(1);
	}
	
	fprintf (stdout, "%s", "Server is running\n");
	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
