/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "erg1.h"

bool_t
xdr_pin_args (XDR *xdrs, pin_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->pina.pina_val, (u_int *) &objp->pina.pina_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->pinb.pinb_val, (u_int *) &objp->pinb.pinb_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ginom_r_args (XDR *xdrs, ginom_r_args *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->n))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->pin.pin_val, (u_int *) &objp->pin.pin_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->r))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_averages_ret (XDR *xdrs, averages_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->avg_a))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->avg_b))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ginom_r_ret (XDR *xdrs, ginom_r_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->epistr.epistr_val, (u_int *) &objp->epistr.epistr_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}
