/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ERG1_H_RPCGEN
#define _ERG1_H_RPCGEN

#define _GNU_SOURCE

#include <rpc/rpc.h>
#include <rpc/clnt.h>     
#include <rpc/svc.h>     

#ifdef __cplusplus
extern "C" {
#endif


struct pin_args {
	int n;
	struct {
		u_int pina_len;
		int *pina_val;
	} pina;
	struct {
		u_int pinb_len;
		int *pinb_val;
	} pinb;
};
typedef struct pin_args pin_args;

struct ginom_r_args {
	int n;
	struct {
		u_int pin_len;
		int *pin_val;
	} pin;
	double r;
};
typedef struct ginom_r_args ginom_r_args;

struct averages_ret {
	double avg_a;
	double avg_b;
};
typedef struct averages_ret averages_ret;

struct ginom_r_ret {
	struct {
		u_int epistr_len;
		double *epistr_val;
	} epistr;
};
typedef struct ginom_r_ret ginom_r_ret;

#define ERG1_PROG 0x2345EDCB
#define ERG1_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ESWT_GINOM 1
extern  int * eswt_ginom_1(pin_args *, CLIENT *);
extern  int * eswt_ginom_1_svc(pin_args *, struct svc_req *);
#define AVERAGES 2
extern  averages_ret * averages_1(pin_args *, CLIENT *);
extern  averages_ret * averages_1_svc(pin_args *, struct svc_req *);
#define GINOM_R 3
extern  ginom_r_ret * ginom_r_1(ginom_r_args *, CLIENT *);
extern  ginom_r_ret * ginom_r_1_svc(ginom_r_args *, struct svc_req *);
extern int erg1_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ESWT_GINOM 1
extern  int * eswt_ginom_1();
extern  int * eswt_ginom_1_svc();
#define AVERAGES 2
extern  averages_ret * averages_1();
extern  averages_ret * averages_1_svc();
#define GINOM_R 3
extern  ginom_r_ret * ginom_r_1();
extern  ginom_r_ret * ginom_r_1_svc();
extern int erg1_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pin_args (XDR *, pin_args*);
extern  bool_t xdr_ginom_r_args (XDR *, ginom_r_args*);
extern  bool_t xdr_averages_ret (XDR *, averages_ret*);
extern  bool_t xdr_ginom_r_ret (XDR *, ginom_r_ret*);

#else /* K&R C */
extern bool_t xdr_pin_args ();
extern bool_t xdr_ginom_r_args ();
extern bool_t xdr_averages_ret ();
extern bool_t xdr_ginom_r_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ERG1_H_RPCGEN */
